[dynet] random seed: 549131646
[dynet] allocating memory: 512MB
[dynet] memory allocation done.
load data
Traceback (most recent call last):
  File "scripts/probe.py", line 1154, in <module>
    probe_iter = ProbeIterator(args, tokenizer)
  File "scripts/probe.py", line 415, in __init__
    self.entity2gender = load_entity_gender('own_gender.txt')
  File "/home/lcur0519/X-FACTR/scripts/check_gender.py", line 49, in load_entity_gender
    with open(filename, 'r') as fin:
FileNotFoundError: [Errno 2] No such file or directory: 'own_gender.txt'
Traceback (most recent call last):
  File "scripts/run_experiment.py", line 36, in <module>
    if experiment.returncode != 0: raise RuntimeError("Experiment failed - Subprocess exit code 1")
RuntimeError: Experiment failed - Subprocess exit code 1
